Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Read in the data from data/pend.txt
X = np.loadtxt("data/pend.txt")
N, D = X.shape
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;66;03m# Read in the data from data/pend.txt[39;00m
[0;32m----> 2[0m X [38;5;241m=[39m np[38;5;241m.[39mloadtxt([38;5;124m"[39m[38;5;124mdata/pend.txt[39m[38;5;124m"[39m)
[1;32m      3[0m N, D [38;5;241m=[39m X[38;5;241m.[39mshape

File [0;32m/opt/anaconda3/lib/python3.12/site-packages/numpy/lib/npyio.py:1373[0m, in [0;36mloadtxt[0;34m(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, quotechar, like)[0m
[1;32m   1370[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(delimiter, [38;5;28mbytes[39m):
[1;32m   1371[0m     delimiter [38;5;241m=[39m delimiter[38;5;241m.[39mdecode([38;5;124m'[39m[38;5;124mlatin1[39m[38;5;124m'[39m)
[0;32m-> 1373[0m arr [38;5;241m=[39m _read(fname, dtype[38;5;241m=[39mdtype, comment[38;5;241m=[39mcomment, delimiter[38;5;241m=[39mdelimiter,
[1;32m   1374[0m             converters[38;5;241m=[39mconverters, skiplines[38;5;241m=[39mskiprows, usecols[38;5;241m=[39musecols,
[1;32m   1375[0m             unpack[38;5;241m=[39munpack, ndmin[38;5;241m=[39mndmin, encoding[38;5;241m=[39mencoding,
[1;32m   1376[0m             max_rows[38;5;241m=[39mmax_rows, quote[38;5;241m=[39mquotechar)
[1;32m   1378[0m [38;5;28;01mreturn[39;00m arr

File [0;32m/opt/anaconda3/lib/python3.12/site-packages/numpy/lib/npyio.py:992[0m, in [0;36m_read[0;34m(fname, delimiter, comment, quote, imaginary_unit, usecols, skiplines, max_rows, converters, ndmin, unpack, dtype, encoding)[0m
[1;32m    990[0m     fname [38;5;241m=[39m os[38;5;241m.[39mfspath(fname)
[1;32m    991[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(fname, [38;5;28mstr[39m):
[0;32m--> 992[0m     fh [38;5;241m=[39m np[38;5;241m.[39mlib[38;5;241m.[39m_datasource[38;5;241m.[39mopen(fname, [38;5;124m'[39m[38;5;124mrt[39m[38;5;124m'[39m, encoding[38;5;241m=[39mencoding)
[1;32m    993[0m     [38;5;28;01mif[39;00m encoding [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    994[0m         encoding [38;5;241m=[39m [38;5;28mgetattr[39m(fh, [38;5;124m'[39m[38;5;124mencoding[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mlatin1[39m[38;5;124m'[39m)

File [0;32m/opt/anaconda3/lib/python3.12/site-packages/numpy/lib/_datasource.py:193[0m, in [0;36mopen[0;34m(path, mode, destpath, encoding, newline)[0m
[1;32m    156[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    157[0m [38;5;124;03mOpen `path` with `mode` and return the file object.[39;00m
[1;32m    158[0m 
[0;32m   (...)[0m
[1;32m    189[0m 
[1;32m    190[0m [38;5;124;03m"""[39;00m
[1;32m    192[0m ds [38;5;241m=[39m DataSource(destpath)
[0;32m--> 193[0m [38;5;28;01mreturn[39;00m ds[38;5;241m.[39mopen(path, mode, encoding[38;5;241m=[39mencoding, newline[38;5;241m=[39mnewline)

File [0;32m/opt/anaconda3/lib/python3.12/site-packages/numpy/lib/_datasource.py:533[0m, in [0;36mDataSource.open[0;34m(self, path, mode, encoding, newline)[0m
[1;32m    530[0m     [38;5;28;01mreturn[39;00m _file_openers[ext](found, mode[38;5;241m=[39mmode,
[1;32m    531[0m                               encoding[38;5;241m=[39mencoding, newline[38;5;241m=[39mnewline)
[1;32m    532[0m [38;5;28;01melse[39;00m:
[0;32m--> 533[0m     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mpath[38;5;132;01m}[39;00m[38;5;124m not found.[39m[38;5;124m"[39m)

[0;31mFileNotFoundError[0m: data/pend.txt not found.

